#!/bin/bash

LOCAL_REPO="/gitclone/LocalProjectCore/"
USERNAME="NataliaPV"
PASSWORD="Spring2019"
REMOTE_REPO="github.com/NataliaPV/ScalaMainRep"

cd $LOCAL_REPO

date_var="$(date)"
date_var="${date_var// /-}" # replaces all spaces with dashes
log_file="log/$date_var.log"
mkdir -p "log" && touch $log_file
day="${log_file:0:14}" # gets the first 10 characters of string


add_commit_push()
{
    git add * >> "$log_file"
    echo "-------Natalia test------" >> "$log_file"
    git commit -a -m "Auto-commit at $date_var" >> "$log_file"
    echo "-------Natalia test-------" >> "$log_file"
    git push -u https://$USERNAME:$PASSWORD@$REMOTE_REPO master >> "$log_file"
    if [[ $? != 0 ]]; then
        echo "Body" | mail -s "push failed" npvbox@mail.ru
        echo "push failed"
        exit 1
    fi
    echo "success!"
}


add_commit_push
    
